version: '3.8'

services:
  # Node.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NODE_PORT}:3000"  # Map external port to internal port
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Map external port 80 to internal port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # MySQL Database Service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"  # Map external port 3306 to internal port 3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"  # Map external port 8080 to internal port 80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USERNAME}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

# Define a named volume for MySQL data persistence
volumes:
  db-data:

# Define the network for the services
networks:
  app-network:
    driver: bridge
